#!/bin/sh
####################################################
#
#  FileType:    SH
#  Date:        Big Bang
#  Author:      Siavash Katebzadeh
#  Email:       mr.katebzadeh@gmail.com
#  Project:     Scripts
#  Copy Right:  :)
#
####################################################

PROJECT_NAME=`hostname`
PROJECT_TYPE='SH'
AUTHOR='Siavash Katebzadeh'
EMAIL='mr.katebzadeh@gmail.com'

usage() {
    echo "Usage: $0 -n <Project Name> [-t <Project Type>] [-a <Author>] [-e <Email> ]" 1>&2
    exit 1
}

check_role(){
    if [ "${ROLE}" != "-" ]; then
        echo "You can use either -s or -m option, but not both!"
        usage
    fi
}

while getopts ":e:a:t:n:" o; do
    case "${o}" in
        n)
            PROJECT_NAME=${OPTARG}
            ;;
        t)
            PROJECT_TYPE=${OPTARG}
            ;;
        a)
            AUTHOR=${OPTARG}
            ;;
        e)
            EMAIL=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ "${PROJECT_NAME}" = "" ]; then
    echo "You need to specify a name for the project."
    usage
fi



