#!/bin/sh
####################################################
#
#  FileName:    weather
#  FileType:    SH
#  Date: 10/05/2018
#  Author:      Siavash Katebzadeh
#  Email:       mr.katebzadeh@gmail.com
#  Project: scripts 
#  Copy Right:  :)
#
####################################################

CITY=$1
TIME=$2
if [[ $CITY == "" ]]; then
    CITY="edinburgh"
fi

if [[ $TIME == "now" ]]; then
    TIME='?0'
fi

curl -s "wttr.in/$CITY$TIME?n"
