#!/usr/bin/env bash

DEFAULT_WALLPAPER="${XDG_DATA_HOME:-$HOME/.local/share/}bg.jpg"
TEMP_WALLPAPER=$(mktemp --suffix=.jpg)

if [ $# -eq 1 ]; then
	WALLPAPER=$1
else
	WALLPAPER=$DEFAULT_WALLPAPER
fi

cp $WALLPAPER $TEMP_WALLPAPER

hyprctl hyprpaper unload "$TEMP_WALLPAPER"
hyprctl hyprpaper preload "$TEMP_WALLPAPER"
monitors=($(hyprctl monitors | grep Monitor | awk '{print $2}' | tr "\n" " "))
for i in "${monitors[@]}"; do hyprctl hyprpaper wallpaper $i,$TEMP_WALLPAPER; done
