#!/usr/bin/env bash

bgloc="${XDG_DATA_HOME:-$HOME/.local/share/}/bg.jpg"

trueloc="$(readlink -f "$1")" &&
	case "$(file --mime-type -b "$trueloc")" in
	image/*) ln -sf "$(readlink -f "$1")" "$bgloc" && notify-send -i "$bgloc" "Changing wallpaper..." ;;
	inode/directory) ln -sf "$(find "$trueloc" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1)" "$bgloc" && notify-send -i "$bgloc" "Random Wallpaper chosen." ;;
	*)
		notify-send.sh "Error" "Not a valid image."
		exit 1
		;;
	esac

hyprctl hyprpaper unload "$bgloc"
hyprctl hyprpaper preload "$bgloc"
monitors=($(hyprctl monitors | grep Monitor | awk '{print $2}' | tr "\n" " "))
for i in "${monitors[@]}"; do hyprctl hyprpaper wallpaper $i,$bgloc; done
