#!/bin/sh
# Notify me with dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5) if my battery is below 25%.
# You can set this to run via cron.

[ "$(cat /sys/class/power_supply/BAT0/status)" = "Charging" ] && exit
[ "$(cat /sys/class/power_supply/BAT0/capacity)" -lt 25 ] &&
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus &&
dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5) -u critical "Battery critically low."
