#! /bin/sh
picom &
setbg &

killall -q sxhkd
sxhkd &

# Check if polybar is already running
if pgrep -x "polybar" > /dev/null; then
    # If it is, kill it
    killall -q polybar
    # Wait until the process is killed
    while pgrep -x "polybar" > /dev/null; do sleep 1; done
fi

# Launch polybar
polybar &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d  "1: " "2: " "3: " "4: " "5: " "6: " "7: " "8: " "9:" 
bspc config border_width         2
bspc config window_gap          12

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc rule -a Brave-browser desktop=^7
bspc rule -a music desktop=^5
bspc rule -a tabbed desktop=^8
bspc rule -a "Microsoft Teams - Preview" desktop=^8
bspc rule -a Slack desktop=^9
bspc rule -a TelegramDesktop desktop=^9

bspc rule -a spterm sticky=on state=floating hidden=on
[ "$(ps -x | grep -c 'spterm')" -eq "1" ] && terminal --class=spterm --title=spter -e bsp_spterm &
