#! /bin/sh
picom &
setbg &
killall -q sxhkd && sxhkd &
killall -q polybar && polybar &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d  "1: " "2: " "3: " "4: " "5: " "6: " "7: " "8: " "9:" 
bspc config border_width         2
bspc config window_gap          12

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
