#!/bin/sh
#
# Import text/calendar files from mutt
# to calcurse.
#

# Make sure calcurse is running
if [ ! -f "$HOME/.config/calcurse/.calcurse.pid" ]; then
	exit 1
fi

# Extract the attachments
TEMPDIR=$(mktemp -d add-to-calcurse.XXXXXXXX)

cat "$@" | uudeview -i -m -n -q -p $TEMPDIR - > /dev/null 2>&1

# Add the calendar file (last attachment) to calcurse
FILE=$(ls $TEMPDIR | sort -r | head -1)
calcurse -D ~/.config/calcurse -i "$TEMPDIR/$FILE" > /dev/null 2>&1

# Remove the temporary dir and trigger a reload in calcurse
rm -rf $TEMPDIR > /dev/null 2>&1
