#!/bin/bash

"$@"

ret=$?
app=$1
icon=checked
[ "$app" != "sudo" ] || app="$1 $2"
[ "$ret" = 0 ] || icon=error
pgrep -x dunst >/dev/null && \
 dunstify "<b>${app}</b> is done. Exit code: ${ret}" --icon="$icon"
exit $ret
