#!/bin/sh
# This is a general notification command for my own ease.
#	$1 should be a message
#	$2 is an optional image for dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5)
# Echos content on terminal and if dunst is running, shows notification.

[ -z "$2" ] || img="-i $2"
echo "$1" && pgrep -x dunst >/dev/null && dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5) $img "$1"
