#!/bin/sh

ag -g ".pdf$" \
    | awk 'BEGIN {FS="\t"; OFS="\t"}; {command="pdftotext -f 1 -l 1 \""$0"\" - 2>/dev/null | tr \"\n\" \"_\" "; command|getline d; close(command); print $0, d}' \
    | fzf -e \
    --preview-window up:50% \
    --preview "pdftotext -f 1 -l 1 '{1}' - " \
    | awk 'BEGIN {FS="\t"; OFS="\t"}; {print $1}' \
    | xargs gio open
