#!/bin/sh
ifinstalled transmission-remote-cli transmission-cli || exit

! pgrep -x transmission-da >/dev/null && transmission-daemon && notify-send "Starting torrent daemon..." && sleep 3 && refbar

$TERMINAL -e transmission-remote-cli
