require('plugins')
require('binding_config')
vim.cmd('source ~/.config/nvim/vimscript/commands.vim')
vim.cmd('source ~/.config/nvim/vimscript/vimwiki.vim')
require('whichkey_config')
require('nv-utils')
require('visual_config')
require('basic_config')
require('startify_config')
require('lsp')
--require('git_config')
require('tree_config')
require('cmp_config')
-- require('autopair_config')
require('gitblame_config')
require('comment_config')
require('lightbulb_config')
require('lspkind_config')
require('gitsigns_config')
require('treesitter_config')
require('galaxyline_config')
require('telescope_config')
require('floaterm_config')
require('header_config')
