#!/bin/bash
# Give dmenu list of all unicode characters to copy.
# Shows the selected character in dunst if running.

# Must have xclip installed to even show menu.
xclip -h >/dev/null || exit

XDG_CONFIG_HOME=~/.config
if [ ! -e $XDG_CONFIG_HOME/dmenutrans ]
then
    languages=$(echo "" | dmen "Please enter your default languages, separated by *space*:")
    if [ "$languages" != '' ]
    then
        echo $languages > $XDG_CONFIG_HOME/dmenutrans
    fi
else
    languages=$({ echo "Exit"; cat $XDG_CONFIG_HOME/dmenutrans; } | sed 's/\ /\\n/g')
    [ "$language" != "Exit" ] || exit
    if [ "$languages" != '' ]
    then
        from=$(echo -e "$languages" | dmen "Translate from")
        if [ "$from" != '' ]
        then
            to=$(echo -e "$languages" | grep -v $from | dmen "Translate from $from to")
            if [ "$to" != '' ]
            then
                while true;
                do
                text="$(xclip -o | dmen "text":)"
                if [ "$text" != '' ]
                then
                    choice=$({ echo "Next word"; echo "Exit"; } | dmen "`trans -b $from:$to $text`")
                    [ "$choice" != "Exit" ] || exit
                    [ "$choice" != "" ] || exit
                fi
                done
            fi
        fi
    fi
fi
