#!/usr/bin/env bash

music_dir="$HOME/Music"

url_text=""
if command -v xclip 2>/dev/null; then
    url_text=$(xclip -selection clip -o)
elif command -v xsel 2>/dev/null; then
    url_text=$(xsel -o -b)
fi

url=$(dmenu -p "Url" <<< "$url_text")

if [[ -z "$url" ]]; then
    echo "No url provided" >&2
    exit 1
fi

song=$(dmenu -p "Song" <<< '')

if [[ -z "$song" ]]; then
    echo "No song name provided" >&2
    exit 2
fi

artist=$(dmenu -i -p "Artist" <<< "$(find "$music_dir" -mindepth 1 -maxdepth 1 -type d -printf '%f\n')")

albums=''
if [[ -n "$artist" ]]; then
    albums="$(find "$music_dir/$artist" -mindepth 1 -maxdepth 1 -type d -printf "%f\n" 2>/dev/null)"
    album=$(dmenu -i -p "Album" <<< "$albums")
fi


mkdir "$music_dir/$artist/$album" -p 2>/dev/null

youtube-dl --write-thumbnail -x --audio-format mp3 -o "$music_dir/$artist/$album/$song.%(ext)s" "$url"

songfile="$music_dir/$artist/$album/$song.mp3"
artfile="$music_dir/$artist/$album/$song.jpg"

if [[ -n "$album" ]]; then
    mid3v2 -t "$song" -a "$artist" -A "$album" -p "$artfile" "$songfile"
elif [[ -n "$artist" ]]; then
    mid3v2 -t "$song" -a "$artist" -p "$artfile" "$songfile"
else
    mid3v2 -t "$song" -p "$artfile" "$songfile"
fi

rm "$artfile" 2>/dev/null

if [[ -n "$DISPLAY" ]]; then
    pgrep -x dunst >/dev/null && dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5) "Music" "${song} added to Music." --icon=starred
fi
