#!/bin/sh

# Gives a dmenu prompt to open websites.
# Without input, will open DuckDuckGo.com.
# If the site exists in sites.csv, will open the site.
# Anything else, it search it.

pgrep -x dmen && exit

choice=$(cat ~/.scripts/i3cmds/sites.csv | dmen " Open Site:" | awk '{print $1}') || exit 1
lines=$( grep $choice ~/.scripts/i3cmds/sites.csv )
if [ "$lines" != ""  ]; then
     $BROWSER $( echo "$lines" | awk '{print $2}' )
fi
