#!/bin/sh


pgrep -x dunst && dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5) --icon=lock "Locking desktop ..."

# Pause music (mocp, mpd and send the pause key to all mpv videos):
mocp -P >/dev/null 2>&1
mpc pause >/dev/null 2>&1
pauseallmpv >/dev/null 2>&1

# In five seconds, turn off display unless key press in last 4 seconds.
sleep 5 && [ 4000 -lt "$(xssstate -i)" ] &&  dm-tool lock
