#!/bin/bash

# Must have xclip installed to even show menu.
xclip -h >/dev/null || exit

url=$( { echo "Exit"; xclip -o; } | dmen "Enter the Youtube URL: ")
[ "$url" != "" ] || exit
[ "$url" != "Exit" ] || exit

mpv --demuxer-lavf-o=protocol_whitelist=[http,https,tls,rtp,tcp,udp,crypto,httpproxy] "${url}"
