#!/usr/bin/env bash

DEFAULT_WALLPAPER="${XDG_DATA_HOME:-$HOME/.local/share}/backgrounds/wall.jpg"

TEMP_WALLPAPER=$(mktemp --suffix=.jpg)

if [ $# -eq 1 ]; then
	WALLPAPER=$1
else
	WALLPAPER=$DEFAULT_WALLPAPER
fi

if [ -f "$WALLPAPER" ]; then
	cp "$WALLPAPER" "$TEMP_WALLPAPER"

	/usr/bin/osascript -e "tell application \"System Events\" to tell every desktop to set picture to \"${WALLPAPER}\" as POSIX file"
	echo "Wallpaper set to $TEMP_WALLPAPER"
else
	echo "Error: File $WALLPAPER does not exist."
	exit 1
fi
