#!/bin/sh

date '+%a %d %b %I:%M%p'

case $BLOCK_BUTTON in
	1) pgrep -x dunst >/dev/null && dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5) "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" ;;
	2) "$TERMINAL" -e calcurse ;;
	3) pgrep -x dunst >/dev/null && dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5) "<b>📅 Time/date module:</b>
- Left click to show month via \`cal\`
- Middle click opens calcurse if installed" ;;
esac

