#!/bin/sh
IP=`curl https://ipinfo.io/ip`
case $BLOCK_BUTTON in
	1) $TERMINAL -e nmtui & pgrep -x dunst > /dev/null && dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5) "<b>Global IP:</b><br>${IP}";;
	3) pgrep -x dunst >/dev/null && dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5) "<b>Internet module:</b>
- Left click for \`nmtui\` for wifi access
📡: no wifi connection
📶: wifi connection with quality
❎: no ethernet
🌐: ethernet working
" ;;
esac

[ "$(cat /sys/class/net/w*/operstate)" = 'down' ] && wifiicon=""

[ ! -n "${wifiicon+var}" ] && wifiicon=$({ grep "^\s*w" /proc/net/wireless | awk '{print "", int($3 * 100 / 70) "%"}'; } | tr "\n" " ")
printf "%s %s" "$wifiicon" "$(cat /sys/class/net/e*/operstate | sed "s/down//;s/up//")"
