#!/bin/sh

# This script is the SUDO_ASKPASS variable, meaning that it will be used as a
# password prompt if needed.
if [ $XDG_SESSION_TYPE = "x11" ]; then
    menu -fn Monospace-18 -P -p "$1" <&- && echo
else
  echo $(echo "$1" | menu -P)

fi
