after-login-command = []

after-startup-command = [
  'exec-and-forget sketchybar',
  # 'exec-and-forget borders'
]

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    'sketchybar --trigger aerospace_workspace_change AEROSPACE_FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE AEROSPACE_PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE',
]

on-focus-changed = [
  # 'move-mouse window-lazy-center',
  'exec-and-forget sketchybar --trigger front_app_switched',
  'exec-and-forget sketchybar --trigger update_windows'
]

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        [{ monitor."built-in.*" = 48 }, 48]
outer.right =      10

[exec.env-vars]
PATH = '${HOME}/bin:${PATH}:${HOME}/.nix-profile/bin:/run/current-system/sw/bin'

[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
cmd-enter = 'exec-and-forget wezterm start --always-new-process'
cmd-w = 'exec-and-forget open -a "Brave Browser"'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'
cmd-0 = 'workspace 10'


# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
cmd-ctrl-1 = 'move-node-to-workspace 1'
cmd-ctrl-2 = 'move-node-to-workspace 2'
cmd-ctrl-3 = 'move-node-to-workspace 3'
cmd-ctrl-4 = 'move-node-to-workspace 4'
cmd-ctrl-5 = 'move-node-to-workspace 5'
cmd-ctrl-6 = 'move-node-to-workspace 6'
cmd-ctrl-7 = 'move-node-to-workspace 7'
cmd-ctrl-8 = 'move-node-to-workspace 8'
cmd-ctrl-9 = 'move-node-to-workspace 9'
cmd-ctrl-0 = 'move-node-to-workspace 10'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = [
  'reload-config',
  'mode main',
  'exec-and-forget sketchybar --reload',
  'exec-and-forget borders',
  'exec-and-forget sleep 0.5 && sketchybar --trigger send_message MESSAGE="Aerospace Reloaded"'
]
r = [
  'flatten-workspace-tree',
  'mode main',
  'exec-and-forget sleep 0.5 && sketchybar --trigger hide_message',
] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = ['layout tiling', 'move-node-to-workspace 7']

[[on-window-detected]]
if.app-id = 'com.apple.Mail'
run = ['layout tiling', 'move-node-to-workspace 8']


[[on-window-detected]]
if.window-title-regex-substring = '^Zotero$'
run = ['layout tiling', 'move-node-to-workspace 5']

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = ['layout tiling', 'move-node-to-workspace 7']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['layout tiling', 'move-node-to-workspace 9']

[[on-window-detected]]
if.app-id = 'com.apple.Notes'
run = ['layout tiling', 'move-node-to-workspace 4']

[[on-window-detected]]
if.window-title-regex-substring = '^Notion$'
run = ['layout tiling', 'move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.tdesktop.Telegram'
run = ['layout tiling', 'move-node-to-workspace 10']
