#!/bin/bash

# Must have xclip installed to even show menu.
xclip -h >/dev/null || exit

hput() {
  eval hash"$1"='$2'
}

hget() {
  eval echo '${hash'"$1"'#hash}'
}

colors=( Background CurrentLine Selection Foreground Comment Cyan Green Orange Pink Purple Red Yellow )
hput Background "#282a36"
hput CurrentLine "#44475a"
hput Selection "#44475a"
hput Foreground "#f8f8f2"
hput Comment "#6272a4"
hput Cyan "#8be9fd"
hput Green "#50fa7b"
hput Orange "#ffb86c"
hput Pink "#ff79c6"
hput Purple "#bd93f9"
hput Red "#ff5555"
hput Yellow "#f1fa8c"

chosen=$({ echo "Exit"; printf '%s\n' "${colors[@]}"; } | dmen "Choose the color: " )
[ "$chosen" != "" ] || exit
[ "$chosen" != "Exit" ] || exit


echo "`hget ${chosen}`" | tr -d '\n' | xclip -selection clipboard

pgrep -x dunst >/dev/null && dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5) "'${chosen}' `hget ${chosen}` copied to primary." --icon=starred
