#!/bin/bash

# Must have xclip installed to even show menu.
xclip -h >/dev/null || exit

url=$( { echo "Exit"; xclip -o; } | dmen "Enter the Youtube URL: ")
[ "$url" != "" ] || exit
[ "$url" != "Exit" ] || exit
title=$(youtube-dl  -e ${url})

chosen=$({ echo "Exit"; youtube-dl -F ${url} | grep "audio only" | awk '{print $1  " "  $7 " " $2}' | sort -r; }  | dmen "Choose the FORMAT for ${title}: " | awk '{print $1}' )

[ "$chosen" != "" ] || exit
[ "$chosen" != "Exit" ] || exit

youtube-dl -f${chosen} -o '~/Music/youtube/%(title)s.%(ext)s' ${url}

pgrep -x dunst >/dev/null && dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5) "'${title}' added to Music." --icon=starred
