#!/bin/bash

cd ~
while true; do
    url=$( { echo "Exit"; echo ".."; ls ;} | dmen "Select your file: `pwd`")
    if [ -d "$url" ]
    then
        cd "$url"
    else
        mpv  "$url"
        break
    fi
done
