#!/bin/sh

# Display contents of selection via dunst if running.
# Separate script for i3.

! pgrep -x dunst >/dev/null && echo "dunst not running." && exit

clip=$(xclip -o -selection clipboard)


prim=$(xclip -o -selection primary)

[ "$prim" != "" ] && dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5) "<b>Clipboard:</b>
$prim"
[ "$clip" != "" ] && dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5) "<b>Primary:</b>
$clip"
