{ pkgs, ... }: {
  packages = with pkgs; [
    direnv
    # LSP servers
    nodePackages.prettier
    jsonnet-language-server
    nixpkgs-fmt
    clang-tools
    rust-analyzer
    lua-language-server
    texlab
    nodePackages.bash-language-server
    cmake-language-server
    vscode-extensions.vadimcn.vscode-lldb
    cpplint
    dockerfile-language-server-nodejs
    vscode-langservers-extracted
    nodePackages.intelephense
    lemminx
    markdownlint-cli
    unstable.basedpyright
    shellcheck
    shfmt
    tailwindcss-language-server
    taplo
    nodePackages.vim-language-server
    yaml-language-server
    #
    patchelf
    asdf-vm
    bat
    atuin
    btop
    coreutils
    curl
    dbus
    dust
    fastfetch
    fd
    fontconfig
    fzf
    gawk
    git
    git-filter-repo
    gpg-tui
    htop
    kitty
    lazydocker
    lazygit
    less
    lsd
    jq
    nix-search-cli
    nushell
    python3
    python311Packages.pynvim
    ripgrep
    stow
    stylua
    tealdeer
    tree-sitter
    wget
    zellij
    yazi
  ];
}
