#!/bin/sh

case $BLOCK_BUTTON in
	1) dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5) "<b>🖥 CPU hogs</b>:
$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)" ;;
	3) dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5) "<b>🖥 CPU module:</b>
- Shows CPU temperature.
- Click to show intensive processes.
- % is of single core." ;;
esac

sensors | awk '/^temp1/ {print $2}'
