#!/bin/sh

case $BLOCK_BUTTON in
	1) dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5) "<b>🧠 Memory hogs:</b>
$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
	3) dunstify -r $(echo $0 | cksum | cut -b 1,2,3,4,5) "<b>🧠 Memory module:</b>
- Shows Memory Used/Total.
- Click to show memory hogs." ;;
esac

free | awk '/^Mem:/ {p=($3/$2)*100} END {printf("%0.1f%", p)}'
