#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim -u $HOME/.config/nvim/simple_init.lua" vimdiff="nvim -u $HOME/.config/nvim/simple_init.lua -d"

# Verbosity and settings that you pretty much just always are going to want.

alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -v"
alias mkd="mkdir -pv"
alias yt="youtube-dl --add-metadata -i"
alias yta="yt -x -f bestaudio/best"
alias ffmpeg="ffmpeg -hide_banne"

# if lsd is installed alias ls, ll and tree to use lsd
[ -x "$(command -v lsd)" ] && alias ls="lsd --icon never" alias ll="lsd -al" alias tree="lsd --tree"

alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ccat="highlight --out-format=ans"
alias ll="ls -al"


# These common commands are just too long! Abbreviate them.
alias ka="killall"
alias g="git"
alias trem="transmission-remote"
alias YT="youtube-viewer"
alias sdn="sudo shutdown -h now"
alias pacfuz="pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S"

alias magit="nvim -c MagitOnly"
alias weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherrepor"
